# Generated by Django 6.1.1 on 2026-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoonPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='moon_plots/')),
                ('plot_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('song', models.PositiveSmallIntegerField(choices=[(1, 'Song 1'), (2, 'Song 2'), (3, 'Song 3'), (4, 'Song 4'), (5, 'Song 5'), (6, 'Song 6'), (7, 'Song 7'), (8, 'Song 8'), (9, 'Song 9'), (10, 'Song 10'), (11, 'Song 11'), (12, 'Song 12'), (13, 'Song 13'), (14, 'Song 14'), (15, 'Song 15'), (16, 'Song 16'), (17, 'Song 17'), (18, 'Song 18'), (19, 'Song 19'), (20, 'Song 20')])),
                ('wants_reply', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
