# Generated by Django 6.1.1 on 2026-09-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moonplot',
            name='url',
            field=models.CharField(default=5, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
