# Generated by Django 6.1.1 on 2026-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_moonplot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='moonplot',
            name='design',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Design 1'), (2, 'Design 2'), (3, 'Design 3'), (4, 'Design 4'), (5, 'Design 5')], default=1),
        ),
        migrations.AddField(
            model_name='moonplot',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
